### ISSUE TITLE
How to render?

### ISSUE THREAD

**Issue by trusktr** [stackgl/headless-gl#114]
Suppose I don't want headless, how would I make this output to the screen?

**Comment by mourner** [comment]
Then you'd want some other library. This one is specifically for headless rendering.

**Comment by trusktr** [comment]
Right, but the README [mentions](https://github.com/stackgl/headless-gl#why-use-this-thing-instead-of-node-webgl)

> Despite the name node-webgl doesn't actually implement WebGL - rather it gives you "WebGL"-flavored bindings to whatever OpenGL driver is configured on your system. If you are starting from an existing WebGL application or library, this means you'll have to do a bunch of work rewriting your WebGL code and shaders to deal with all the idiosyncrasies and bugs present on whatever platforms you try to run on. The upside though is that node-webgl exposes a lot of non-WebGL stuff that might be useful for games like window creation, mouse and keyboard input, requestAnimationFrame emulation, and some native OpenGL features.

Basically, it would be great to use headless-gl because it solves those problems, makes it easier to write gl without caring about those idiosyncrasies. That's awesome!

Do I need to use `gl.readPixels` then just find some way to put those pixels on the screen myself? Any recommendation on what to do?

**Comment by mourner** [comment]
It unfortunately only works under Node.js, and rendering is many orders of magnitude slower than what you'd get in a browser. It's purpose is mainly writing automated tests for WebGL applications.

**Comment by greggman** [comment]
@trusktr , what are you trying to accomplish?

headless-gl is for node which doesn't have a screen. If you want to render to the screen how about Electron?

**Comment by trusktr** [comment]
I'm looking for something like this:

http://waset.org/publications/8553/a-standalone-webgl-supporting-architecture

I can't find the source for that. Maybe he'll email me back. I'll update if he does.

I want a pure (as in not having the whole extra browser overhead) JavaScript-WebGL environment.

Then, for example, we can make interesting standalone apps, for example implement a web browser from scratch (except for the underlying WebGL part). Maybe a standalone JavaScript-WebGL-Canvas2D environment would be most ideal.

More background on why I don't just want to use Electron/WebKit/Blink: https://bugs.chromium.org/p/chromium/issues/detail?id=749873

**Comment by greggman** [comment]
Should probably take this discussion somewhere else but....

Just WebGL + JavaScript is unlikely to be enough. Next you'll need a way to load images. Images are not part of WebGL they're part of the browser. Then you'll need a way to get video. Video is not part of WebGL it's part of the browser. Next you'll need a way to play audio. Audio is not part of WebGL. Next you'll probably want to support text, Supporting full unicode text including languages like Japanese, Chinese, Korean, Arabic, Thai is a huge amount of work. Next you'll want input for those languages meaning IMEs or IME support. Next you'll find you want some communication so you'll need XMLHttpRequest and/or WebSockets and/or WebRTC.

My point is the browser is doing a ton of stuff.

On top of that unless you support it all you'll also be unlikely to use libraries meant for browsers.

Otherwise, if you just want to make some native app and plug JavaScript into it as it's scripting language then for graphics portability you might consider [ANGLE](https://github.com/google/angle)

**Comment by trusktr** [comment]
Although I'd like to make a browser (or at least browser-like env) using pure JS, I can start with existing modules that may not be written in JS.

Node.js `http` module, then

> Next you'll need a way to load images

https://www.npmjs.com/package/image

> Then you'll need a way to get video

https://www.npmjs.com/package/video or something, don't really need video yet.

> Next you'll need a way to play audio

https://www.npmjs.com/package/audio-speaker
https://github.com/audiojs/web-audio-api

> Next you'll probably want to support text

https://www.npmjs.com/package/omgcanvas
https://www.npmjs.com/package/canvas

> Next you'll want input for those languages meaning IMEs or IME support.

That can wait, once the PoC is out, people will contribute!

> Next you'll find you want some communication so you'll need XMLHttpRequest

https://www.npmjs.com/package/xmlhttprequest

> WebSockets 

https://www.npmjs.com/package/ws

> and/or WebRTC

https://www.npmjs.com/package/webrtc-native

Ah, then I need to start connecting it all together:

https://www.npmjs.com/package/jsdom

The hardest part will be rendering the DOM.

What I'll do is start with Electron, then start rendering everything into WebGL, and start replacing features one by one with the NPM packages, then eventually replace those with pure JS!

Sounds like a good project eh? 

Look how many stars this abandoned (failed?) project had: https://github.com/breach/breach_core

Web devs being able to hack the core of a browser, because they know JavaScript. Now that'd be something!

Okay, okay, well anyways, I just want a plain JS-WebGL env.
