### ISSUE TITLE
Why can't readPixels image data be of type Uint8ClampedArray?

### ISSUE THREAD

**Issue by talltyler** [stackgl/headless-gl#120]
This line forces the type to be Uint8Array
https://github.com/stackgl/headless-gl/blob/509e16ca78a41064e380b76ac762ad305093c588/webgl.js#L3156

If we also allow for Uint8ClampedArray you can interoperate with 2d canvas apis without needing to convert from one type to another which drastically slows everything down.

**Comment by mourner** [comment]
Did you try doing the same with native WebGL in the browser? As far as I remember, it throws an error whenever you feed the WebGL API `Uint8ClampedArray` — it expects a `Uint8Array` instead. However, you can convert one to another without copy, e.g. `new Uint8Array(arr.buffer)` creates a view into the original buffer rather than copy.

**Comment by tzvetelin-vassilev** [comment]
This issue is fixed in browsers. Usage of Uint8ClampedArray is safe and works well both in WebGLRenderingContext and in WebGL2RenderingContext. Interoperability between WebGLRenderingContext and CanvasRenderingContext2D is a good reason to  update this check to

`
!(pixels instanceof Uint8Array || pixels instanceof Uint8ClampedArray)
`

I have tested in this way and everything looks fine in both places - browsers and nodejs

**Comment by dhritzkiv** [comment]
@tzvetelin-vassilev would you mind submitting this change as a PR? And please add/edit tests if needed.
