### ISSUE TITLE
How is this exactly headless?

### ISSUE THREAD

**Issue by adminy** [stackgl/headless-gl#150]
This only runs on Operating systems with graphics installed. How is https://github.com/stackgl/headless-gl/blob/ec9ab3621f1befa8a6f2fd590a4fbb5ed91da2b0/src/webgl.cc#L53

Headless? Or is EGL_DEFAULT_DISPLAY a fake?

More of a question than an issue, but I’ll appreciate to learn. Thank you.

**Comment by dhritzkiv** [comment]
See [System dependencies](https://github.com/stackgl/headless-gl#system-dependencies). Basically, in the case of a system with no built in graphics (and no graphics drivers), such as a Linux server instance, mesa, x11, and xvfb work together to be the graphics layer.

Specifically, xvfb is the display in this case, as it provides a virtual frame buffer to draw to.

**Comment by adminy** [comment]
So in `ANGLE` it is not possible to create that virtual frame buffer without depending on System Drivers or Operating system’s frame buffer?

**Comment by dhritzkiv** [comment]
Correct. Any way you go about it, the graphics stack is going to be complicated.

What are you trying to achieve that isn't possible on your system?

**Comment by adminy** [comment]
I have angle compiled, and I have a v8 instance but I don’t have node, The environment isn’t on macos linux or windows. It seems silly to create an x11 server just so that you could use it’s buffer, because from my understanding that’s all angle really needs from the x11 server. Couldn’t that just be another array like how readPixels takes an array?

**Comment by dhritzkiv** [comment]
Note: this library is only supported on macOS, Linux, and Windows, and only with the nodejs runtime. This is partly due to Angle supporting macOS, Linux, and Windows.

I believe you're underestimating the importance of mesa, x11, and xvfb (on linux, at least). To my knowledge, it's not simply a matter of creating a buffer and handing it off to Angle. I may be wrong, however, and I would be very interested if you can come up with a robust alternative solution.

**Comment by robertleeplummerjr** [comment]
Something you could do is use, for example, a library like GPU.js (shameless plug, and reason I got interested in and eventually contributed to headless-gl) and simply write your shaders in javascript, and if there is no graphics stack available, it reverts to simple javascript & arrays, but will use GPU when they are available.

https://gpu.rocks for more info.  I'm working on releasing v2 at the moments, so docs for v2 release candidates are a bit out of date but will be fixed in the coming days.

**Comment by kkaefer** [comment]
You don't need an X server to run OpenGL commands. `headless-gl` uses EGL to acquire resources; there's no reference to X servers in the code. You _can_ use an X server as the backend though.

However, you're stating that your server doesn't have a GPU at all. You could use a CPU implementation of OpenGL, e.g. https://swiftshader.googlesource.com/SwiftShader. SwiftShader provides both a desktop and an OpenGL ES implementation. Since WebGL is based on Open GL ES, you can use that one directly instead of using ANGLE as an intermediary layer.

**Comment by neuro-sys** [comment]
@kkaefer

> there's no reference to X servers in the code.

I'm curious why is the binary linked against X libraries in that case:

```
ldd ./build/Release/webgl.node
    linux-vdso.so.1 (0x00007ffffd491000)
    libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007fb9f9fa0000)
    libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007fb9f9f80000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb9f9f70000)
    libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb9f9d80000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb9f9c31000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb9f9c0e000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb9f9a10000)
    libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fb9f99e0000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fb9fa36b000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb9f99c0000)
    libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007fb9f99b0000)
    libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fb9f99a0000)
    libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fb9f9970000)
```

> You can use an X server as the backend though.

Do you know how to _not_ use an X server as the backend?

**Comment by JCMais** [comment]
were you able to make it work without x11 @neuro-sys ?

**Comment by neuro-sys** [comment]
@JCMais I used X11, mesa and xvfb-run to run in a headless environment (it's all software, no display or graphics driver is needed). This was for the test environment.
