### ISSUE TITLE
Delete all branches that are no longer active

### ISSUE THREAD

**Issue by robertleeplummerjr** [stackgl/headless-gl#161]
Just housekeeping.  @dhritzkiv you may be a good candidate to take care fo this.

**Comment by dhritzkiv** [comment]
Done.

I kept the gl branch (manifested in #116) as there's some good work that may be useful in the future (if there's renewed demand for alternative backends - see #125 as well). However, I feel it more important to update ANGLE itself before trying to support multiple backends.

**Comment by robertleeplummerjr** [comment]
Ty for your hard work!  Is there an issue where ANGLE is being upgraded?  I was able to upgrade it myself for OSX using a new script here: https://github.com/HeadlessGL/google-angle-binaries

I had planned on making scripts for each environment and then just hosting them somewhere, so to save everyone from ~the idiotic direction to "build it yourself" because of the pompous arrogance that is Google~ having to do the work themselves.

**Comment by robertleeplummerjr** [comment]
Note: I made that organization and project before being added as a developer.

**Comment by dhritzkiv** [comment]
To answer your question, I don't believe there's an issue or PR for upgrading ANGLE (though, there are lots of small issues that warranted upgrading ANGLE, mostly in the way of extension support and webgl2 support).

---

Right! I remember this. Thanks for taking on the unenviable task of understanding their build instructions.

Now that you're a collaborator, is there a way to bring this over into this repo, whether it's a pre-requisite step in the build, or a submodule (as it is currently)? Whatever makes it easy for repo developers, the CI process, and ultimately for end users that may have to compile on each install (say, because a prebuilt binary may not exist).

Since I can't gauge how critical it is to upgrade ANGLE for webgl2 support (you're a better judge of this, based on GPUJS) and since I have no pressing need for it myself (haven't been doing much server-side gl lately), this might have to be your undertaking, if you're willing and have free time. I'll definitely be here for support + review, and will help in getting all the platforms supported.

Feel free to open an issue for upgrading ANGLE, outlining the goals of doing so, and the steps required.
