### ISSUE TITLE
Creating a window

### ISSUE THREAD

**Issue by bnolan** [stackgl/headless-gl#58]
What is involved in creating a window to render to? Do I do it through an angle call?

**Comment by mikolalysenko** [comment]
It would involve modifying the context creation process.  This is the relevant chunk of code that you'd have to change:

https://github.com/stackgl/headless-gl/blob/master/src/webgl.cc#L52-L112

I'd be willing to put in some hooks to support this, but I don't want to put all the platform specific window creation code and dependencies in this project.

**Comment by simonbuchan** [comment]
From the looks of it, if JS could pass in an `EGLNativeWindowType` value as defined in `<EGL/eglplatform.h>` - always a pointer - and using `eglCreateWindowSurface()` instead of `eglCreatePbufferSurface()` should be all that's needed *to render*. That's no more platform specific code than you already have.

That said, there are some environment differences from `<canvas>`, the couple I'm aware of:
- WebGL doesn't have an equivalent to `eglSwapBuffers()`, AFAICT the browser is expected to swap your context with the rest of the page content, so roughly "when your code stops running".
  - Related is `requestAnimationFrame(cb)`, presumably this could be simply "run `cb` immediately after the next buffer swap", so that seems like you could do it yourself, except that you would want to keep running any other node callbacks, which would be blocked by the next call to swap buffers in the Node JS thread until the next vsync (at least, with the sensible default `eglSwapInterval()` of 1). Could web workers fix this?
- WebGL talks about context loss, not sure if this is a thing with ANGLE but if it is you would need to expose hooks for that too if so.

**Comment by simonbuchan** [comment]
I've done some experimentation since: I don't think it would be too useful to provide hooks as the window must be quite specifically created for ANGLE use, and the EGL display must(?) be created from the native display (e.g. from `GetDC(hwnd)` on windows) - fortunately ANGLE already supplies a (very!) cross-platform window implementation in `utils` - unfortunately it also manages all the EGL context creation so I've been trying to re-produce the relevant content, but I've not yet managed to get anything other than black content out of it yet. That said, it looks like integrating directly on top of it and discarding the existing rendering context creation might not be too rough, but it would be a fork of this project.

**Comment by dhritzkiv** [comment]
Closing as part of clean up. Feel free to re-open this issue.

**Comment by simonbuchan** [comment]
If anyone's curious, I created the from-scratch context creation I talked about as a project here: https://github.com/simonbuchan/node-angle
Be aware it only exposes a tiny subset of GL at the moment: basically only enough to get a triangle on screen for testing.
What I ran into doing that is that the node event loop basically doesn't really work very well with a present call (which blocks until the next v-sync), so ideally you would to spin up a rendering thread and that opens up a whole new world of trouble. I might get back to it at some point, but it's pretty clear that it would not look anything like this project.

**Comment by bnolan** [comment]
People might be interested in [exokit](https://github.com/exokitxr/exokit), they seem to have some webgl bindings for node.js.

**Comment by dhritzkiv** [comment]
Thanks @simonbuchan and @bnolan for chiming in with updates and suggestions!

**Comment by andykais** [comment]
one more suggestion: people who want webgl in node may want to check out [electron](https://electronjs.org/). Electron is essentially a wrapper around chromium (what google chrome uses internally) in which you have more control over the look & feel as well as access to the filesystem. Here is an example [webgl electron example app](https://github.com/zamronypj/webgl-electron). The downside is that you will be running a whole web browser whenever you boot up your electron app, and chromium likes to capitalize on free memory.

Also just more news for people who are interested in webgl for serious graphics, WebGPU is attempting to supercede webgl with the capability to utilize modern graphics cards better (heres a neat video from google io that helps explain how https://www.youtube.com/watch?v=K2JzIUIHIhc)

**Comment by robertleeplummerjr** [comment]
Really cool video and news.
